	<div class="row"> <div class="col-md-4 col-lg-3"> 
		<div class="card" style="width: 18rem;"> 
			<img src="../../assets/img/default.png" class="card-img-top" alt="..."> 
			<div class="card-body"> <h5 class="card-title">Suroto Pangestu Wijaya</h5> 
			<p class="card-text"> <span class="fw-semibold">
				Kesalahan :</span>Tidak Membawa Topi</p> 
				<!-- <a href="#" class="btn btn-primary text-center">Det</a> --> 
				</div> </div> </div> <div class="col-md-4 col-lg-3"> 
					<div class="card" style="width: 18rem;"> 
                        <img src="../../assets/img/default.png" class="card-img-top" alt="..."> 
                        <div class="card-body"> <h5 class="card-title">Suroto Pangestu Wijaya</h5>
                         <p class="card-text"> <span class="fw-semibold">Kesalahan :</span>Tidak Membawa Topi</p> <!-- <a href="#" class="btn btn-primary text-center">Det</a> --> </div> </div> </div> <div class="col-md-4 col-lg-3"> <div class="card" style="width: 18rem;"> <img src="../../assets/img/default.png" class="card-img-top" alt="..."> <div class="card-body"> <h5 class="card-title">Suroto Pangestu Wijaya</h5> <p class="card-text"> <span class="fw-semibold">Kesalahan :</span>Tidak Membawa Topi</p> <!-- <a href="#" class="btn btn-primary text-center">Det</a> --> </div> </div> </div> <div class="col-md-4 col-lg-3"> <div class="card" style="width: 18rem;"> <img src="../../assets/img/default.png" class="card-img-top" alt="..."> <div class="card-body"> <h5 class="card-title">Suroto Pangestu Wijaya</h5> <p class="card-text"> <span class="fw-semibold">Kesalahan :</span>Tidak Membawa Topi</p> <!-- <a href="#" class="btn btn-primary text-center">Det</a> --> </div> </div> </div> <div class="col-md-4 col-lg-3"> <div class="card" style="width: 18rem;"> <img src="../../assets/img/default.png" class="card-img-top" alt="..."> <div class="card-body"> <h5 class="card-title">Suroto Pangestu Wijaya</h5> <p class="card-text"> <span class="fw-semibold">Kesalahan :</span>Tidak Membawa Topi</p> <!-- <a href="#" class="btn btn-primary text-center">Det</a> --> </div> </div> </div> <div class="col-md-4 col-lg-3"> <div class="card" style="width: 18rem;"> <img src="../../assets/img/default.png" class="card-img-top" alt="..."> <div class="card-body"> <h5 class="card-title">Suroto Pangestu Wijaya</h5> <p class="card-text"> <span class="fw-semibold">Kesalahan :</span>Tidak Membawa Topi</p> <!-- <a href="#" class="btn btn-primary text-center">Det</a> --> </div> </div> </div> <div class="col-md-4 col-lg-3"> <div class="card" style="width: 18rem;"> <img src="../../assets/img/default.png" class="card-img-top" alt="..."> <div class="card-body"> <h5 class="card-title">Suroto Pangestu Wijaya</h5> <p class="card-text"> <span class="fw-semibold">Kesalahan :</span>Tidak Membawa Topi</p> <!-- <a href="#" class="btn btn-primary text-center">Det</a> --> </div> </div> </div> <div class="col-md-4 col-lg-3"> </div> </div> </div>
        <!-- Tambahkan card lain sesuai kebutuhan -->
      </div>